name: Lab3

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas scikit-learn matplotlib seaborn

      - name: Run analysis script
        run: python s25123.py

      - name: Upload results
        uses: actions/upload-artifact@v3
        with:
          name: report
          path: |
            extended_results_report.md
            variable_distribution.png
            correlation_matrix.png
            score_distribution.png
            score_by_gender.png
            predicted_vs_actual.png
            residuals_distribution.png
